version: "3.8"

networks:
  backend:
    external: false
    name: backend
services:
  brewerymongodb:
    networks:
      - backend
    image: mongo:latest
    container_name: brewerymongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  beer-service-image:
    build: .
    restart: always
    networks:
      - backend
    image: beer-app-image
    container_name: beer-service-image
    ports:
      - 8080:8080
    depends_on:
      - brewerymongodb

volumes:
  mongodb:
    external: false